// <auto-generated />
namespace VOneDal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class m35 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m35));
        
        string IMigrationMetadata.Id
        {
            get { return "201907091154502_m35"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
